import type { ResourceCategory, ResourceItem, ResourceType } from "./resourcesTypes";

export const resourceCategories: ResourceCategory[] = [
  "Marketing",
  "Sales",
  "Operations",
  "Branding",
  "Customer Service",
];

export const resourceTypes: ResourceType[] = [
  "template",
  "guide",
  "checklist",
  "script",
  "calendar",
  "worksheet",
];

export const resources: ResourceItem[] = [
  {
    id: "airport-flyer-template",
    title: "Airport Flyer Template",
    description: "A polished one-page flyer for private airport transportation offers.",
    category: "Marketing",
    type: "template",
    featured: true,
  },
  {
    id: "facebook-launch-posts",
    title: "Facebook Launch Posts",
    description: "Launch announcement copy for neighborhood groups and local pages.",
    category: "Marketing",
    type: "script",
  },
  {
    id: "referral-campaign-flyer",
    title: "Referral Campaign Flyer",
    description: "A simple referral offer asset for current riders and local partners.",
    category: "Marketing",
    type: "template",
  },
  {
    id: "airport-content-calendar",
    title: "Airport Content Calendar",
    description: "A 30-day posting rhythm for airport transfer visibility.",
    category: "Marketing",
    type: "calendar",
  },
  {
    id: "customer-outreach-script",
    title: "Customer Outreach Script",
    description: "A direct message script for turning warm contacts into first riders.",
    category: "Sales",
    type: "script",
    featured: true,
  },
  {
    id: "sms-follow-up-templates",
    title: "SMS Follow-up Templates",
    description: "Short follow-up messages for quotes, bookings, and repeat rides.",
    category: "Sales",
    type: "template",
  },
  {
    id: "cold-call-script",
    title: "Cold Call Script",
    description: "A concise call framework for local hotels, offices, and care providers.",
    category: "Sales",
    type: "script",
  },
  {
    id: "sales-pipeline-worksheet",
    title: "Sales Pipeline Worksheet",
    description: "Track prospects, outreach status, and follow-up dates in one place.",
    category: "Sales",
    type: "worksheet",
  },
  {
    id: "daily-driver-checklist",
    title: "Daily Driver Checklist",
    description: "A pre-shift checklist for vehicle readiness, rider comfort, and safety.",
    category: "Operations",
    type: "checklist",
    featured: true,
  },
  {
    id: "weekly-business-planner",
    title: "Weekly Business Planner",
    description: "Plan outreach, rides, follow-ups, and admin tasks for the week.",
    category: "Operations",
    type: "worksheet",
  },
  {
    id: "booking-workflow-guide",
    title: "Booking Workflow Guide",
    description: "Map the client journey from inquiry to completed ride.",
    category: "Operations",
    type: "guide",
  },
  {
    id: "ride-confirmation-checklist",
    title: "Ride Confirmation Checklist",
    description: "Confirm pickup details, timing, luggage, and special instructions.",
    category: "Operations",
    type: "checklist",
  },
  {
    id: "business-card-template",
    title: "Business Card Template",
    description: "A clean card layout for direct bookings and local networking.",
    category: "Branding",
    type: "template",
  },
  {
    id: "logo-placement-guide",
    title: "Logo Placement Guide",
    description: "Practical guidance for using your brand mark across simple assets.",
    category: "Branding",
    type: "guide",
  },
  {
    id: "brand-color-reference",
    title: "Brand Color Reference",
    description: "A worksheet for choosing consistent colors for your transport brand.",
    category: "Branding",
    type: "worksheet",
  },
  {
    id: "driver-profile-branding-checklist",
    title: "Driver Profile Branding Checklist",
    description: "Make your public profile feel trustworthy, clear, and professional.",
    category: "Branding",
    type: "checklist",
  },
  {
    id: "review-request-script",
    title: "Review Request Script",
    description: "Ask happy riders for reviews without sounding pushy.",
    category: "Customer Service",
    type: "script",
    featured: true,
  },
  {
    id: "thank-you-message-templates",
    title: "Thank You Message Templates",
    description: "Post-ride messages that build trust and encourage repeat bookings.",
    category: "Customer Service",
    type: "template",
  },
  {
    id: "complaint-resolution-guide",
    title: "Complaint Resolution Guide",
    description: "A calm process for resolving issues and protecting client trust.",
    category: "Customer Service",
    type: "guide",
  },
  {
    id: "rider-experience-checklist",
    title: "Rider Experience Checklist",
    description: "Small details that make private rides feel more premium and reliable.",
    category: "Customer Service",
    type: "checklist",
  },
];
