import type { BusinessOwner, FulfillmentTask } from "./adminTypes";

export const mockBusinessOwners: BusinessOwner[] = [
  {
    id: "owner-001",
    ownerName: "Annette Black",
    businessName: "Knoxville Airport Rides",
    city: "Knoxville, TN",
    airports: "TYS",
    domain: "annette.ourdomain.com",
    plan: "DFY",
    status: "active",
    websiteStatus: "live",
    acuityStatus: "connected",
    launchProgress: 86,
    supportTickets: 1,
    joinedAt: "2026-06-08",
  },
  {
    id: "owner-002",
    ownerName: "Maya Collins",
    businessName: "Austin Private Transfers",
    city: "Austin, TX",
    airports: "AUS, SAT",
    domain: "mayarides.ourdomain.com",
    plan: "DIY",
    status: "onboarding",
    websiteStatus: "draft",
    acuityStatus: "not_connected",
    launchProgress: 43,
    supportTickets: 0,
    joinedAt: "2026-06-18",
  },
  {
    id: "owner-003",
    ownerName: "Sofia Ramirez",
    businessName: "Tampa Trusted Transit",
    city: "Tampa, FL",
    airports: "TPA, PIE",
    domain: "sofiatransfers.ourdomain.com",
    plan: "DFY",
    status: "attention",
    websiteStatus: "needs_review",
    acuityStatus: "needs_review",
    launchProgress: 67,
    supportTickets: 3,
    joinedAt: "2026-05-29",
  },
  {
    id: "owner-004",
    ownerName: "Erica Stone",
    businessName: "Charlotte Executive Airport Rides",
    city: "Charlotte, NC",
    airports: "CLT",
    domain: "ericastone.ourdomain.com",
    plan: "DIY",
    status: "active",
    websiteStatus: "live",
    acuityStatus: "connected",
    launchProgress: 71,
    supportTickets: 1,
    joinedAt: "2026-06-01",
  },
  {
    id: "owner-005",
    ownerName: "Nina Patel",
    businessName: "Phoenix Reliable Transfers",
    city: "Phoenix, AZ",
    airports: "PHX, AZA",
    domain: "ninapatel.ourdomain.com",
    plan: "DFY",
    status: "paused",
    websiteStatus: "draft",
    acuityStatus: "not_connected",
    launchProgress: 24,
    supportTickets: 2,
    joinedAt: "2026-06-22",
  },
];

export const mockFulfillmentTasks: FulfillmentTask[] = [
  {
    id: "task-001",
    ownerName: "Annette Black",
    title: "Review booking page copy",
    status: "in_progress",
    dueDate: "2026-07-08",
  },
  {
    id: "task-002",
    ownerName: "Sofia Ramirez",
    title: "Connect preferred domain",
    status: "blocked",
    dueDate: "2026-07-07",
  },
  {
    id: "task-003",
    ownerName: "Nina Patel",
    title: "Collect final headshot",
    status: "not_started",
    dueDate: "2026-07-10",
  },
  {
    id: "task-004",
    ownerName: "Annette Black",
    title: "QA airport booking workflow",
    status: "delivered",
    dueDate: "2026-07-04",
  },
];
