import { Download, Inbox, Loader2, Receipt } from "lucide-react";
import { useGetRiderPaymentHistoryQuery, useLazyGetRiderPaymentInvoiceQuery } from "../store/api/Payment/payment.api";
import type { PaymentRecord } from "../store/api/Payment/payment.type";

const formatDate = (iso: string) => new Date(iso).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
function downloadInvoice(value: Blob | { invoiceUrl?: string }) { if (value instanceof Blob) { const url = URL.createObjectURL(value); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "invoice.pdf"; anchor.click(); URL.revokeObjectURL(url); } else if (value.invoiceUrl) window.open(value.invoiceUrl, "_blank", "noopener,noreferrer"); }
function category(payment: PaymentRecord) { return payment.items.some((item) => item.type.toLowerCase().includes("addon")) ? "Add-Ons" : "Launch Package"; }
function product(payment: PaymentRecord) { const addOn = category(payment) === "Add-Ons"; return addOn ? "Booking Setup Add-on" : `${payment.items[0]?.name || "Private Airport Business"}`; }

export default function BillingPage() {
  const { data, isLoading, isError } = useGetRiderPaymentHistoryQuery();
  const [getInvoice, { isFetching: invoiceLoading }] = useLazyGetRiderPaymentInvoiceQuery();
  const orders = data?.payments ?? [];
  const handleInvoice = async (id: string) => { try { downloadInvoice(await getInvoice(id).unwrap()); } catch { /* keep card actionable for retry */ } };
  return <div className="space-y-6"><div><h2 className="text-2xl font-bold text-slate-900">Payment &amp; Billing</h2><p className="mt-1 text-sm text-slate-500">View your payment history, invoices, and receipts for your one-time purchases.</p></div>{isLoading && <div className="grid place-items-center py-20 text-dashboard-rider"><Loader2 className="h-7 w-7 animate-spin" /></div>}{isError && <div className="rounded-xl bg-red-50 p-6 text-center text-sm text-red-700">Failed to load payment history. Please try again.</div>}{!isLoading && !isError && orders.length === 0 && <div className="grid place-items-center gap-2 rounded-xl bg-white p-16 text-slate-500 shadow-sm"><Inbox className="h-8 w-8 text-slate-300" /><p className="text-sm">No paid payments yet.</p></div>}<div className="space-y-5">{orders.map((payment) => <article key={payment.id} className="rounded-2xl bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-4 border-b border-slate-100 pb-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-green-50 text-green-600"><Receipt className="h-5 w-5" /></span><div><p className="text-sm font-semibold text-green-600">{category(payment)}</p><h3 className="mt-1 font-semibold text-slate-900">{product(payment)}</h3></div></div><span className={`w-fit rounded-lg px-3 py-1.5 text-xs font-semibold ${payment.status === "paid" ? "bg-green-100 text-green-700" : "bg-slate-100 text-slate-500"}`}>{payment.status}</span></div><div className="grid gap-5 pt-5 sm:grid-cols-2 lg:grid-cols-5"><div><p className="text-xs text-slate-400">Order ID</p><p className="mt-1 text-sm font-medium text-slate-800">{payment.orderNumber || `#QTA-${payment.id.slice(0, 4).toUpperCase()}`}</p></div><div><p className="text-xs text-slate-400">Purchase Date</p><p className="mt-1 text-sm font-medium text-slate-800">{formatDate(payment.paidAt || payment.createdAt)}</p></div><div><p className="text-xs text-slate-400">Amount</p><p className="mt-1 text-sm font-medium text-slate-800">${(payment.totalAmount / 100).toFixed(2)}</p></div><div><p className="text-xs text-slate-400">Payment Method</p><p className="mt-1 text-sm font-medium text-slate-800">{payment.paymentBrand || "Stripe"} {payment.paymentLast4 ? `•••• ${payment.paymentLast4}` : ""}</p></div><div className="flex items-end lg:justify-end">{payment.status === "paid" && <button type="button" onClick={() => handleInvoice(payment.id)} disabled={invoiceLoading} className="flex items-center gap-2 rounded-lg bg-dashboard-rider px-4 py-2.5 text-xs font-semibold text-white hover:bg-dashboard-rider-dark disabled:opacity-50"><Download className="h-4 w-4" />Download Invoice</button>}</div></div></article>)}</div></div>;
}
