import type { LocaleDictionary } from "./localizationTypes";

export const localizationData: LocaleDictionary = {
  en: {
    common: {
      appName: "QuitTheApp",
      languageEnglish: "English",
      languageSpanish: "Spanish",
      toggleLanguage: "Toggle language",
      continue: "Continue",
      back: "Back",
      next: "Next",
      close: "Close",
      resetDemo: "Reset demo",
    },
    funnel: {
      standard: {
        eyebrow: "Independent driver launch",
        headline: "Build your transportation business beyond the app.",
        subheadline:
          "A guided launch path for drivers who want direct clients, cleaner operations, and a business they control.",
        primaryCta: "Launch My Business",
        secondaryCta: "Learn More",
        benefits: [
          "Position your private transportation offer",
          "Prepare your driver page and booking flow",
          "Launch with a repeatable outreach plan",
        ],
        trustSignals: ["Frontend-only demo", "No real payment", "Designed for local operators"],
      },
      women: {
        eyebrow: "Women-led transportation",
        headline: "Launch a safer, sharper private transportation offer.",
        subheadline:
          "Create a client-ready service built around trust, repeat riders, and professional local demand.",
        primaryCta: "Launch My Business",
        secondaryCta: "Learn More",
        benefits: [
          "Clarify your ideal rider niche",
          "Package safety and trust signals",
          "Build a repeatable launch plan",
        ],
        trustSignals: ["Women-focused positioning", "No real payment", "Built for independent drivers"],
      },
      seniors: {
        eyebrow: "Senior mobility service",
        headline: "Create a reliable transportation service for older adults.",
        subheadline:
          "Shape your offer for families, caregivers, senior communities, and dependable local mobility.",
        primaryCta: "Launch My Business",
        secondaryCta: "Learn More",
        benefits: [
          "Define senior-friendly service standards",
          "Map local referral partners",
          "Prepare outreach for caregivers and communities",
        ],
        trustSignals: ["Senior mobility niche", "No real payment", "Local launch framework"],
      },
      couples: {
        eyebrow: "Couples business launch",
        headline: "Turn two operators into one coordinated transportation brand.",
        subheadline:
          "Map roles, offers, client intake, and launch assets for a family-run transportation business.",
        primaryCta: "Launch My Business",
        secondaryCta: "Learn More",
        benefits: [
          "Clarify each partner's role",
          "Build one shared launch workflow",
          "Create a coordinated rider experience",
        ],
        trustSignals: ["Couples launch path", "No real payment", "Shared operating plan"],
      },
    },
    checkout: {
      title: "Mock checkout",
      secureCheckout: "Secure Checkout",
      stripeInspiredBadge: "Stripe-inspired demo",
      baseProductName: "QuitTheApp Launch System",
      baseProductDescription: "Frontend-only checkout simulation for the $495 base product.",
      dfyUpgradeName: "Done-For-You upgrade",
      dfyUpgradeDescription: "Add the $245 DFY delivery path to switch your dashboard pipeline.",
      oneTimeFeeLabel: "$495 one-time fee",
      optionalUpgradeLabel: "$245 optional upgrade",
      subtotalLabel: "Subtotal",
      upgradeLabel: "Upgrade",
      totalLabel: "Total",
      completePurchase: "Complete mock purchase",
      cancel: "Cancel",
      securePaymentNotice: "No real payment will be processed. This is a secure-looking frontend demo.",
      closeCheckout: "Close checkout",
      successTitle: "Purchase complete",
      successMessage: "Your QuitTheApp launch system is ready.",
      preparingWorkspace: "Preparing your workspace...",
    },
    marketing: {
      launchCta: "Launch My Business",
      learnMoreCta: "Learn More",
      smallTrustText: "Frontend-only preview. Checkout opens in Phase 7.",
      benefitsTitle: "Everything you need to move from app driver to business owner.",
      benefits: [
        {
          title: "Business launch plan",
          description: "Turn your transportation idea into a clear offer, service area, and launch path.",
        },
        {
          title: "Airport-ready positioning",
          description: "Create private transfer offers for riders who need reliable airport service.",
        },
        {
          title: "Revenue ownership",
          description: "Build direct customer relationships instead of depending only on platform demand.",
        },
        {
          title: "Repeat rider systems",
          description: "Set up simple follow-up and referral habits that keep good clients coming back.",
        },
        {
          title: "Booking guidance",
          description: "Understand the tools and workflows needed to accept and manage private rides.",
        },
        {
          title: "Trust-first service",
          description: "Package your professionalism, safety, and reliability into a client-ready offer.",
        },
      ],
      howItWorksTitle: "How it works",
      howItWorksSteps: [
        {
          title: "Purchase QuitTheApp",
          description: "Start with the launch system and choose whether you want the optional setup upgrade later.",
        },
        {
          title: "Complete business setup",
          description: "Use the guided resources to define your offer, driver page, booking flow, and outreach plan.",
        },
        {
          title: "Launch your independent transportation business",
          description: "Begin contacting direct clients and building a repeatable local transportation asset.",
        },
      ],
      pricingTitle: "Simple launch pricing",
      oneTimePayment: "One-time payment",
      whatsIncluded: "What's Included",
      pricingIncludes: [
        "Business Launch Blueprint",
        "Airport Transportation Templates",
        "Marketing Scripts",
        "Customer Acquisition Resources",
        "Progress Dashboard",
        "Booking System Guidance",
      ],
      optionalUpgradeTitle: "Optional Upgrade",
      comparisonTitle: "Simple comparison",
      comparisonBase: "Base system: DIY launch resources and dashboard guidance.",
      comparisonUpgrade: "Done-For-You Setup: additional setup support for faster implementation.",
      trustTitle: "Built for independent operators",
      trustCards: [
        {
          title: "Own 100% of Your Revenue",
          description: "Create direct relationships and keep more control over pricing and client experience.",
        },
        {
          title: "No Monthly Subscription",
          description: "Start with a one-time launch system instead of another recurring platform bill.",
        },
        {
          title: "Built for Independent Drivers",
          description: "Designed around airport transfers, local mobility, and private rider relationships.",
        },
        {
          title: "Launch Faster with Proven Systems",
          description: "Use guided templates and workflows instead of inventing every step from scratch.",
        },
      ],
      faqTitle: "Frequently asked questions",
      faqs: [
        {
          question: "What is QuitTheApp?",
          answer: "QuitTheApp is a frontend-only PWA concept for helping drivers launch an independent transportation business.",
        },
        {
          question: "Who is this for?",
          answer: "It is for drivers who want direct clients, clearer positioning, and a business beyond app-based rides.",
        },
        {
          question: "Is this a subscription?",
          answer: "The planned base product is presented as a one-time payment in this funnel UI.",
        },
        {
          question: "Do I need technical experience?",
          answer: "No. The system is designed to guide business setup, offers, outreach, and booking decisions step by step.",
        },
        {
          question: "How long does setup take?",
          answer: "Timing depends on your market and readiness, but the flow is designed to help you organize the essentials quickly.",
        },
        {
          question: "What is the Done-For-You option?",
          answer: "The optional upgrade represents extra setup support. Checkout and delivery logic are not implemented yet.",
        },
      ],
      footerHeadline: "Ready to build your transportation business?",
      footerText: "Start with a focused launch system built for drivers who want more control, better clients, and a real operating path.",
    },
    onboarding: {
      title: "Tell us about your transportation launch.",
      subtitle: "This intake seeds your client-side dashboard experience.",
      businessSetupTitle: "Business Setup",
      progressPurchase: "Purchase",
      progressBusinessSetup: "Business Setup",
      completedLabel: "Completed",
      currentLabel: "Current",
      businessInformationTitle: "Business Information",
      headshotUploadTitle: "Headshot Upload",
      summaryTitle: "Launch Summary",
      summaryName: "Name",
      summaryTargetMarket: "Target Market",
      summaryRegionalAirports: "Regional Airports",
      summaryPreferredDomain: "Preferred Domain",
      summaryHeadshot: "Headshot Preview",
      uploadButton: "Choose image",
      replaceImage: "Replace image",
      uploadPlaceholder: "JPEG, PNG, or WEBP. Preview stays on this device only.",
      fullNameLabel: "Full name",
      fullNamePlaceholder: "Test Driver",
      targetCityLabel: "Target city",
      targetCityPlaceholder: "Austin",
      regionalAirportsLabel: "Regional airports",
      regionalAirportsPlaceholder: "AUS, SAT",
      preferredDomainLabel: "Preferred domain",
      preferredDomainPlaceholder: "testdrivertransport.com",
      headshotLabel: "Headshot preview URL",
      headshotHelper: "Optional for now. A blob URL or image preview path can be used later.",
      initializeDashboard: "Initialize dashboard",
      validationRequired: "This field is required.",
      validationPreferredDomain: "Use letters, numbers, hyphens, or dots only.",
      validationImageType: "Please choose a JPEG, PNG, or WEBP image.",
      emptySummaryValue: "Not provided yet",
    },
    dashboard: {
      title: "Launch dashboard",
      subtitle: "Track your client-side launch path and next steps.",
      diyPathTitle: "DIY launch modules",
      dfyPathTitle: "Done-For-You delivery pipeline",
      progressLabel: "Launch progress",
      motivationalMessage: "Great progress! Complete all modules to launch your business.",
      resourcesLabel: "Resources",
      statusNotStarted: "Not started",
      statusInProgress: "In progress",
      statusComplete: "Complete",
    },
  },
  es: {
    common: {
      appName: "QuitTheApp",
      languageEnglish: "Ingles",
      languageSpanish: "Espanol",
      toggleLanguage: "Cambiar idioma",
      continue: "Continuar",
      back: "Volver",
      next: "Siguiente",
      close: "Cerrar",
      resetDemo: "Reiniciar demo",
    },
    funnel: {
      standard: {
        eyebrow: "Lanzamiento para conductores independientes",
        headline: "Construye tu negocio de transporte mas alla de la app.",
        subheadline:
          "Un camino guiado para conductores que quieren clientes directos, operaciones mas claras y un negocio bajo su control.",
        primaryCta: "Lanzar mi negocio",
        secondaryCta: "Aprender mas",
        benefits: [
          "Define tu oferta de transporte privado",
          "Prepara tu pagina de conductor y flujo de reservas",
          "Lanza con un plan repetible de contacto",
        ],
        trustSignals: ["Demo solo frontend", "Sin pago real", "Pensado para operadores locales"],
      },
      women: {
        eyebrow: "Transporte liderado por mujeres",
        headline: "Lanza una oferta de transporte privado mas segura y profesional.",
        subheadline:
          "Crea un servicio listo para clientes basado en confianza, pasajeros recurrentes y demanda local.",
        primaryCta: "Lanzar mi negocio",
        secondaryCta: "Aprender mas",
        benefits: [
          "Aclara tu nicho ideal de pasajeros",
          "Presenta senales de seguridad y confianza",
          "Construye un plan de lanzamiento repetible",
        ],
        trustSignals: ["Enfoque para mujeres", "Sin pago real", "Hecho para conductoras independientes"],
      },
      seniors: {
        eyebrow: "Servicio de movilidad para adultos mayores",
        headline: "Crea un servicio de transporte confiable para adultos mayores.",
        subheadline:
          "Adapta tu oferta para familias, cuidadores, comunidades de adultos mayores y movilidad local confiable.",
        primaryCta: "Lanzar mi negocio",
        secondaryCta: "Aprender mas",
        benefits: [
          "Define estandares de servicio para adultos mayores",
          "Mapea socios de referencia locales",
          "Prepara contacto para cuidadores y comunidades",
        ],
        trustSignals: ["Nicho de movilidad senior", "Sin pago real", "Marco de lanzamiento local"],
      },
      couples: {
        eyebrow: "Lanzamiento de negocio para parejas",
        headline: "Convierte dos operadores en una marca de transporte coordinada.",
        subheadline:
          "Organiza roles, ofertas, ingreso de clientes y activos de lanzamiento para un negocio familiar de transporte.",
        primaryCta: "Lanzar mi negocio",
        secondaryCta: "Aprender mas",
        benefits: [
          "Aclara el rol de cada persona",
          "Construye un flujo de lanzamiento compartido",
          "Crea una experiencia coordinada para pasajeros",
        ],
        trustSignals: ["Ruta para parejas", "Sin pago real", "Plan operativo compartido"],
      },
    },
    checkout: {
      title: "Pago simulado",
      secureCheckout: "Pago seguro",
      stripeInspiredBadge: "Demo inspirado en Stripe",
      baseProductName: "Sistema de lanzamiento QuitTheApp",
      baseProductDescription: "Simulacion frontend del producto base de $495.",
      dfyUpgradeName: "Mejora Done-For-You",
      dfyUpgradeDescription: "Agrega la ruta DFY de $245 para cambiar el panel a una entrega guiada.",
      oneTimeFeeLabel: "Pago unico de $495",
      optionalUpgradeLabel: "Mejora opcional de $245",
      subtotalLabel: "Subtotal",
      upgradeLabel: "Mejora",
      totalLabel: "Total",
      completePurchase: "Completar pago simulado",
      cancel: "Cancelar",
      securePaymentNotice: "No se procesara ningun pago real. Esta es una demo frontend con apariencia segura.",
      closeCheckout: "Cerrar pago",
      successTitle: "Compra completada",
      successMessage: "Tu sistema de lanzamiento QuitTheApp esta listo.",
      preparingWorkspace: "Preparando tu espacio de trabajo...",
    },
    marketing: {
      launchCta: "Lanzar mi negocio",
      learnMoreCta: "Aprender mas",
      smallTrustText: "Vista previa solo frontend. El pago llega en la Fase 7.",
      benefitsTitle: "Todo lo que necesitas para pasar de conductor de app a dueno de negocio.",
      benefits: [
        {
          title: "Plan de lanzamiento",
          description: "Convierte tu idea de transporte en una oferta clara, una zona de servicio y una ruta de lanzamiento.",
        },
        {
          title: "Posicionamiento para aeropuertos",
          description: "Crea ofertas de traslados privados para pasajeros que necesitan servicio confiable al aeropuerto.",
        },
        {
          title: "Control de ingresos",
          description: "Construye relaciones directas con clientes en vez de depender solo de la demanda de plataformas.",
        },
        {
          title: "Sistemas para pasajeros recurrentes",
          description: "Configura seguimiento y referidos simples para que buenos clientes vuelvan.",
        },
        {
          title: "Guia de reservas",
          description: "Entiende las herramientas y flujos necesarios para aceptar y administrar viajes privados.",
        },
        {
          title: "Servicio basado en confianza",
          description: "Presenta tu profesionalismo, seguridad y confiabilidad en una oferta lista para clientes.",
        },
      ],
      howItWorksTitle: "Como funciona",
      howItWorksSteps: [
        {
          title: "Compra QuitTheApp",
          description: "Comienza con el sistema de lanzamiento y decide despues si quieres la mejora opcional de configuracion.",
        },
        {
          title: "Completa la configuracion del negocio",
          description: "Usa los recursos guiados para definir tu oferta, pagina de conductor, reservas y plan de contacto.",
        },
        {
          title: "Lanza tu negocio independiente de transporte",
          description: "Empieza a contactar clientes directos y a construir un activo local de transporte repetible.",
        },
      ],
      pricingTitle: "Precio simple de lanzamiento",
      oneTimePayment: "Pago unico",
      whatsIncluded: "Lo que incluye",
      pricingIncludes: [
        "Blueprint de lanzamiento del negocio",
        "Plantillas de transporte al aeropuerto",
        "Guiones de marketing",
        "Recursos para conseguir clientes",
        "Panel de progreso",
        "Guia para sistema de reservas",
      ],
      optionalUpgradeTitle: "Mejora opcional",
      comparisonTitle: "Comparacion simple",
      comparisonBase: "Sistema base: recursos DIY y guia en el panel.",
      comparisonUpgrade: "Configuracion Done-For-You: soporte adicional para implementar mas rapido.",
      trustTitle: "Creado para operadores independientes",
      trustCards: [
        {
          title: "Conserva el 100% de tus ingresos",
          description: "Crea relaciones directas y controla mejor tus precios y la experiencia del cliente.",
        },
        {
          title: "Sin suscripcion mensual",
          description: "Comienza con un sistema de lanzamiento de pago unico, no otra factura recurrente.",
        },
        {
          title: "Hecho para conductores independientes",
          description: "Pensado para traslados al aeropuerto, movilidad local y relaciones con pasajeros privados.",
        },
        {
          title: "Lanza mas rapido con sistemas probados",
          description: "Usa plantillas y flujos guiados en vez de inventar cada paso desde cero.",
        },
      ],
      faqTitle: "Preguntas frecuentes",
      faqs: [
        {
          question: "Que es QuitTheApp?",
          answer: "QuitTheApp es un concepto de PWA frontend para ayudar a conductores a lanzar un negocio independiente de transporte.",
        },
        {
          question: "Para quien es?",
          answer: "Es para conductores que quieren clientes directos, posicionamiento claro y un negocio mas alla de las apps de viajes.",
        },
        {
          question: "Es una suscripcion?",
          answer: "El producto base planeado se presenta como un pago unico en esta interfaz de funnel.",
        },
        {
          question: "Necesito experiencia tecnica?",
          answer: "No. El sistema guia la configuracion del negocio, ofertas, contacto y decisiones de reservas paso a paso.",
        },
        {
          question: "Cuanto tarda la configuracion?",
          answer: "Depende de tu mercado y preparacion, pero el flujo esta pensado para organizar lo esencial rapidamente.",
        },
        {
          question: "Que es la opcion Done-For-You?",
          answer: "La mejora opcional representa soporte adicional de configuracion. El pago y la entrega aun no estan implementados.",
        },
      ],
      footerHeadline: "Listo para construir tu negocio de transporte?",
      footerText: "Comienza con un sistema de lanzamiento enfocado para conductores que quieren mas control, mejores clientes y una ruta real de operacion.",
    },
    onboarding: {
      title: "Cuentanos sobre tu lanzamiento de transporte.",
      subtitle: "Este formulario prepara tu experiencia de panel del lado del cliente.",
      businessSetupTitle: "Configuracion del negocio",
      progressPurchase: "Compra",
      progressBusinessSetup: "Configuracion del negocio",
      completedLabel: "Completado",
      currentLabel: "Actual",
      businessInformationTitle: "Informacion del negocio",
      headshotUploadTitle: "Carga de foto",
      summaryTitle: "Resumen de lanzamiento",
      summaryName: "Nombre",
      summaryTargetMarket: "Mercado objetivo",
      summaryRegionalAirports: "Aeropuertos regionales",
      summaryPreferredDomain: "Dominio preferido",
      summaryHeadshot: "Vista previa de foto",
      uploadButton: "Elegir imagen",
      replaceImage: "Reemplazar imagen",
      uploadPlaceholder: "JPEG, PNG o WEBP. La vista previa queda solo en este dispositivo.",
      fullNameLabel: "Nombre completo",
      fullNamePlaceholder: "Conductor de prueba",
      targetCityLabel: "Ciudad objetivo",
      targetCityPlaceholder: "Austin",
      regionalAirportsLabel: "Aeropuertos regionales",
      regionalAirportsPlaceholder: "AUS, SAT",
      preferredDomainLabel: "Dominio preferido",
      preferredDomainPlaceholder: "transportedeprueba.com",
      headshotLabel: "URL de vista previa de foto",
      headshotHelper: "Opcional por ahora. Mas adelante puedes usar una URL blob o una ruta de imagen.",
      initializeDashboard: "Inicializar panel",
      validationRequired: "Este campo es obligatorio.",
      validationPreferredDomain: "Usa solo letras, numeros, guiones o puntos.",
      validationImageType: "Elige una imagen JPEG, PNG o WEBP.",
      emptySummaryValue: "Aun no proporcionado",
    },
    dashboard: {
      title: "Panel de lanzamiento",
      subtitle: "Sigue tu ruta de lanzamiento del lado del cliente y tus proximos pasos.",
      diyPathTitle: "Modulos de lanzamiento DIY",
      dfyPathTitle: "Pipeline de entrega Done-For-You",
      progressLabel: "Progreso del lanzamiento",
      motivationalMessage: "Buen progreso. Completa todos los modulos para lanzar tu negocio.",
      resourcesLabel: "Recursos",
      statusNotStarted: "No iniciado",
      statusInProgress: "En progreso",
      statusComplete: "Completo",
    },
  },
};
