import type { LocaleDictionary } from "./localizationTypes";

export const localizationData: LocaleDictionary = {
  en: {
    common: {
      appName: "QuitTheApp",
      languageEnglish: "English",
      languageSpanish: "Spanish",
      toggleLanguage: "Toggle language",
      continue: "Continue",
      back: "Back",
      next: "Next",
      close: "Close",
      resetDemo: "Reset demo",
    },
    checkout: {
      title: "Mock checkout",
      secureCheckout: "Secure Checkout",
      stripeInspiredBadge: "Stripe-inspired demo",
      baseProductName: "QuitTheApp Launch System",
      baseProductDescription: "Frontend-only checkout simulation for the $495 base product.",
      dfyUpgradeName: "Done-For-You upgrade",
      dfyUpgradeDescription: "Add the $245 DFY delivery path to switch your dashboard pipeline.",
      oneTimeFeeLabel: "$495 one-time fee",
      optionalUpgradeLabel: "$245 optional upgrade",
      subtotalLabel: "Subtotal",
      upgradeLabel: "Upgrade",
      totalLabel: "Total",
      completePurchase: "Complete mock purchase",
      cancel: "Cancel",
      securePaymentNotice: "No real payment will be processed. This is a secure-looking frontend demo.",
      closeCheckout: "Close checkout",
      successTitle: "Purchase complete",
      successMessage: "Your QuitTheApp launch system is ready.",
      preparingWorkspace: "Preparing your workspace...",
    },
    marketing: {
      launchCta: "Launch My Business",
      oneTimePayment: "One-time payment",
      whatsIncluded: "What's Included",
      pricingIncludes: [
        "Business Launch Blueprint",
        "Airport Transportation Templates",
        "Marketing Scripts",
        "Customer Acquisition Resources",
        "Progress Dashboard",
        "Booking System Guidance",
      ],
      faqTitle: "Frequently asked questions",
      faqs: [
        {
          question: "What is QuitTheApp?",
          answer: "QuitTheApp is a frontend-only PWA concept for helping drivers launch an independent transportation business.",
        },
        {
          question: "Who is this for?",
          answer: "It is for drivers who want direct clients, clearer positioning, and a business beyond app-based rides.",
        },
        {
          question: "Is this a subscription?",
          answer: "The planned base product is presented as a one-time payment in this funnel UI.",
        },
        {
          question: "Do I need technical experience?",
          answer: "No. The system is designed to guide business setup, offers, outreach, and booking decisions step by step.",
        },
        {
          question: "How long does setup take?",
          answer: "Timing depends on your market and readiness, but the flow is designed to help you organize the essentials quickly.",
        },
        {
          question: "What is the Done-For-You option?",
          answer: "The optional upgrade represents extra setup support. Checkout and delivery logic are not implemented yet.",
        },
      ],
    },
    onboarding: {
      title: "Tell us about your transportation launch.",
      subtitle: "This intake seeds your client-side dashboard experience.",
      businessSetupTitle: "Business Setup",
      progressPurchase: "Purchase",
      progressBusinessSetup: "Business Setup",
      completedLabel: "Completed",
      currentLabel: "Current",
      businessInformationTitle: "Business Information",
      headshotUploadTitle: "Headshot Upload",
      summaryTitle: "Launch Summary",
      summaryName: "Name",
      summaryTargetMarket: "Target Market",
      summaryRegionalAirports: "Regional Airports",
      summaryPreferredDomain: "Preferred Domain",
      summaryHeadshot: "Headshot Preview",
      uploadButton: "Choose image",
      replaceImage: "Replace image",
      uploadPlaceholder: "JPEG, PNG, or WEBP. Preview stays on this device only.",
      fullNameLabel: "Full name",
      fullNamePlaceholder: "Test Driver",
      targetCityLabel: "Target city",
      targetCityPlaceholder: "Austin",
      regionalAirportsLabel: "Regional airports",
      regionalAirportsPlaceholder: "AUS, SAT",
      preferredDomainLabel: "Preferred domain",
      preferredDomainPlaceholder: "testdrivertransport.com",
      headshotLabel: "Headshot preview URL",
      headshotHelper: "Optional for now. A blob URL or image preview path can be used later.",
      initializeDashboard: "Initialize dashboard",
      validationRequired: "This field is required.",
      validationPreferredDomain: "Use letters, numbers, hyphens, or dots only.",
      validationImageType: "Please choose a JPEG, PNG, or WEBP image.",
      emptySummaryValue: "Not provided yet",
    },
    dashboard: {
      title: "Launch dashboard",
      subtitle: "Track your client-side launch path and next steps.",
      diyPathTitle: "DIY launch modules",
      dfyPathTitle: "Done-For-You delivery pipeline",
      progressLabel: "Launch progress",
      motivationalMessage: "Great progress! Complete all modules to launch your business.",
      resourcesLabel: "Resources",
      statusNotStarted: "Not started",
      statusInProgress: "In progress",
      statusComplete: "Complete",
    },
  },
  es: {
    common: {
      appName: "QuitTheApp",
      languageEnglish: "Ingles",
      languageSpanish: "Espanol",
      toggleLanguage: "Cambiar idioma",
      continue: "Continuar",
      back: "Volver",
      next: "Siguiente",
      close: "Cerrar",
      resetDemo: "Reiniciar demo",
    },
    checkout: {
      title: "Pago simulado",
      secureCheckout: "Pago seguro",
      stripeInspiredBadge: "Demo inspirado en Stripe",
      baseProductName: "Sistema de lanzamiento QuitTheApp",
      baseProductDescription: "Simulacion frontend del producto base de $495.",
      dfyUpgradeName: "Mejora Done-For-You",
      dfyUpgradeDescription: "Agrega la ruta DFY de $245 para cambiar el panel a una entrega guiada.",
      oneTimeFeeLabel: "Pago unico de $495",
      optionalUpgradeLabel: "Mejora opcional de $245",
      subtotalLabel: "Subtotal",
      upgradeLabel: "Mejora",
      totalLabel: "Total",
      completePurchase: "Completar pago simulado",
      cancel: "Cancelar",
      securePaymentNotice: "No se procesara ningun pago real. Esta es una demo frontend con apariencia segura.",
      closeCheckout: "Cerrar pago",
      successTitle: "Compra completada",
      successMessage: "Tu sistema de lanzamiento QuitTheApp esta listo.",
      preparingWorkspace: "Preparando tu espacio de trabajo...",
    },
    marketing: {
      launchCta: "Lanzar mi negocio",
      oneTimePayment: "Pago unico",
      whatsIncluded: "Lo que incluye",
      pricingIncludes: [
        "Blueprint de lanzamiento del negocio",
        "Plantillas de transporte al aeropuerto",
        "Guiones de marketing",
        "Recursos para conseguir clientes",
        "Panel de progreso",
        "Guia para sistema de reservas",
      ],
      faqTitle: "Preguntas frecuentes",
      faqs: [
        {
          question: "Que es QuitTheApp?",
          answer: "QuitTheApp es un concepto de PWA frontend para ayudar a conductores a lanzar un negocio independiente de transporte.",
        },
        {
          question: "Para quien es?",
          answer: "Es para conductores que quieren clientes directos, posicionamiento claro y un negocio mas alla de las apps de viajes.",
        },
        {
          question: "Es una suscripcion?",
          answer: "El producto base planeado se presenta como un pago unico en esta interfaz de funnel.",
        },
        {
          question: "Necesito experiencia tecnica?",
          answer: "No. El sistema guia la configuracion del negocio, ofertas, contacto y decisiones de reservas paso a paso.",
        },
        {
          question: "Cuanto tarda la configuracion?",
          answer: "Depende de tu mercado y preparacion, pero el flujo esta pensado para organizar lo esencial rapidamente.",
        },
        {
          question: "Que es la opcion Done-For-You?",
          answer: "La mejora opcional representa soporte adicional de configuracion. El pago y la entrega aun no estan implementados.",
        },
      ],
    },
    onboarding: {
      title: "Cuentanos sobre tu lanzamiento de transporte.",
      subtitle: "Este formulario prepara tu experiencia de panel del lado del cliente.",
      businessSetupTitle: "Configuracion del negocio",
      progressPurchase: "Compra",
      progressBusinessSetup: "Configuracion del negocio",
      completedLabel: "Completado",
      currentLabel: "Actual",
      businessInformationTitle: "Informacion del negocio",
      headshotUploadTitle: "Carga de foto",
      summaryTitle: "Resumen de lanzamiento",
      summaryName: "Nombre",
      summaryTargetMarket: "Mercado objetivo",
      summaryRegionalAirports: "Aeropuertos regionales",
      summaryPreferredDomain: "Dominio preferido",
      summaryHeadshot: "Vista previa de foto",
      uploadButton: "Elegir imagen",
      replaceImage: "Reemplazar imagen",
      uploadPlaceholder: "JPEG, PNG o WEBP. La vista previa queda solo en este dispositivo.",
      fullNameLabel: "Nombre completo",
      fullNamePlaceholder: "Conductor de prueba",
      targetCityLabel: "Ciudad objetivo",
      targetCityPlaceholder: "Austin",
      regionalAirportsLabel: "Aeropuertos regionales",
      regionalAirportsPlaceholder: "AUS, SAT",
      preferredDomainLabel: "Dominio preferido",
      preferredDomainPlaceholder: "transportedeprueba.com",
      headshotLabel: "URL de vista previa de foto",
      headshotHelper: "Opcional por ahora. Mas adelante puedes usar una URL blob o una ruta de imagen.",
      initializeDashboard: "Inicializar panel",
      validationRequired: "Este campo es obligatorio.",
      validationPreferredDomain: "Usa solo letras, numeros, guiones o puntos.",
      validationImageType: "Elige una imagen JPEG, PNG o WEBP.",
      emptySummaryValue: "Aun no proporcionado",
    },
    dashboard: {
      title: "Panel de lanzamiento",
      subtitle: "Sigue tu ruta de lanzamiento del lado del cliente y tus proximos pasos.",
      diyPathTitle: "Modulos de lanzamiento DIY",
      dfyPathTitle: "Pipeline de entrega Done-For-You",
      progressLabel: "Progreso del lanzamiento",
      motivationalMessage: "Buen progreso. Completa todos los modulos para lanzar tu negocio.",
      resourcesLabel: "Recursos",
      statusNotStarted: "No iniciado",
      statusInProgress: "En progreso",
      statusComplete: "Completo",
    },
  },
};
